services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/psn_analyser
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=psn-analyser
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --quiet --logpath /dev/null

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      # - ME_CONFIG_MONGODB_SERVER=atlas-psn-analyser.ytloxii.mongodb.net
      # - ME_CONFIG_BASICAUTH_USERNAME=Vercel-Admin-atlas-psn-analyser
      # - ME_CONFIG_BASICAUTH_PASSWORD=BN9OYARYYsfHmEaP
    # depends_on:
    #   - mongodb

volumes:
  mongodb_data: