# Dockerfile.dev
FROM node:25-alpine3.22

WORKDIR /app

# Instalar dependências do sistema
RUN apk add --no-cache \
    git \
    openssh-client

# Copiar package.json
COPY package*.json ./
COPY tsconfig.json ./

# Instalar dependências
RUN npm install -g pnpm
RUN pnpm install --no-frozen-lockfile --ignore-scripts=false

# Copiar código fonte
COPY . .

# Expor porta
EXPOSE 3000

# Comando de desenvolvimento
CMD ["npm", "run", "dev"]
