FROM node:25-alpine3.22

WORKDIR /app

RUN apk add --no-cache git openssh-client

# Copia arquivos de configuração
COPY package*.json ./
COPY tsconfig.json ./
COPY pnpm-workspace.yaml ./

RUN npm install -g pnpm

RUN pnpm install --no-frozen-lockfile

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]